{{config(
    materialized='incremental',
    tags= ['staging', 'silver', 'attacks', 'sharks','monthly'],
    unique_key='ATTACK_ID',
)}}

WITH CLEANED_VALUES AS (
    SELECT DISTINCT
        ORIGINAL_ORDER AS ATTACK_ID,
        CAST("DATE" AS DATE) AS DATE_CLEAN,
        CAST("YEAR" AS INTEGER) AS YEAR_CLEAN,
        CASE
            WHEN TYPE IS NULL OR TYPE = '?' THEN 'Unverified'
            ELSE TYPE
        END AS ATTACK_TYPE,
        CASE
            WHEN UPPER(COUNTRY) IN ('COLUMBIA', 'COLOMBIA') THEN 'COLOMBIA'
            WHEN UPPER(COUNTRY) IN ('UNITED ARAB EMIRATES', 'UNITED ARAB EMIRATES (UAE)') THEN 'UNITED ARAB EMIRATES'
            WHEN UPPER(COUNTRY) IN ('ST MARTIN', 'ST. MARTIN', 'ST. MAARTIN') THEN 'ST MARTIN'
            WHEN UPPER(COUNTRY) IN ('RED SEA', 'RED SEA?') THEN 'RED SEA'
            WHEN UPPER(COUNTRY) IN ('INDIAN OCEAN', 'INDIAN OCEAN?') THEN 'INDIAN OCEAN'
            WHEN UPPER(COUNTRY) IN ('SUDAN', 'SUDAN?') THEN 'SUDAN'
            ELSE COUNTRY
        END AS COUNTRY_CLEAN,
        AREA,
        LOCATION,
        ACTIVITY,
        FATAL_Y_N,
        CASE
            WHEN UPPER(FATAL_Y_N) ILIKE '%Y%' THEN True
            WHEN UPPER(FATAL_Y_N) IN ('N', 'F') THEN False
            ELSE NULL
        END AS FATAL_OUTCOME,
        SPECIES,
        SOURCE_FILE,
        LOAD_TIMESTAMP_UTC AS INGESTION_TIMESTAMP_UTC,
        CURRENT_TIMESTAMP() AS CLEANED_TIMESTAMP_UTC
    FROM {{ source('bronze_source', 'RAW_SHARK_ATTACKS') }}
)
SELECT
    ATTACK_ID,
    DATE_CLEAN,
    YEAR_CLEAN,
    ATTACK_TYPE,
    COUNTRY_CLEAN,
    FATAL_Y_N,
    FATAL_OUTCOME,
    SOURCE_FILE,
    INGESTION_TIMESTAMP_UTC,
    CLEANED_TIMESTAMP_UTC
FROM CLEANED_VALUES
WHERE (ATTACK_ID IS NOT NULL) 
    AND (DATE_CLEAN IS NOT NULL OR YEAR_CLEAN IS NOT NULL)
    AND (YEAR(DATE_CLEAN) >= 1500 OR YEAR_CLEAN >= 1500)