name: Shark-Gator Pipeline

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install quality tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check code formatting
        run: |
          black ingestion/ tests/

  test:
    name: Code Tests
    runs-on: ubuntu-latest
    needs: quality

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run Python tests
        run: pytest tests/
          pytest --cov=. --cov-report=xml

      - name: Install dbt
        run: pip install dbt-core dbt-snowflake

      - name: Run dbt tests
        working-directory: dbt/shark_gator_dbt
        run: dbt test    
